services:
  Vangrg\RequestMapperBundle\Mapper\RequestMapperInterface: '@Vangrg\RequestMapperBundle\Mapper\RequestMapper'

  Vangrg\RequestMapperBundle\Mapper\RequestMapper:
    public: false
    arguments:
      - '@Symfony\Component\Serializer\SerializerInterface'

  vangrg.request_mapper.annotation_driver:
    class: Vangrg\RequestMapperBundle\Annotation\Driver\RequestParamMapperDriver
    public: false
    arguments:
      - '@Vangrg\RequestMapperBundle\Mapper\RequestMapperInterface'
      - '@Doctrine\Common\Annotations\Reader'
      - '@Symfony\Component\Validator\Validator\ValidatorInterface'
    tags:
      - { name: kernel.event_subscriber }