services:
  vangrg.request_mapper.prepare_validation_response:
    class: Vangrg\RequestMapperBundle\EventListener\ValidationResponseListener
    public: false
    arguments:
      - '@Symfony\Component\Serializer\SerializerInterface'
      -
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 999 }