services:
  Vangrg\RequestMapperBundle\EventListener\ValidationResponseListener:
    arguments:
      - '@Symfony\Component\Serializer\SerializerInterface'
      -
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 999 }